termux tweaks

diff --git a/bin/termux-url-opener b/bin/termux-url-opener
--- a/bin/termux-url-opener
+++ b/bin/termux-url-opener
@@ -1,13 +1,37 @@
 #!/data/data/com.termux/files/usr/bin/bash
 
-if echo "$1" | grep -iq "teeturtle.com"
+domain="$(echo "$1" | grep -iPo '(https://)(www\\.)?[^/]+' | sed 's/\(https:\/\/\|www\.\)//g')" || true
+trackingNum=$(echo "$1" | grep -iPo '([\d ]{10,40}|[a-z\d]{10-40})') || true
+
+echo "input: $1"
+echo "domain: $domain"
+echo "trackingNum: $trackingNum"
+
+# if you provided a url
+if [ -n "$domain" ]
 then
-	teeDir="$HOME/storage/downloads/TeeTurtle/"
-	mkdir -p "$teeDir"
-	$HOME/bin/download-teeturtle "$1" "$teeDir"
-	termux-media-scan "$teeDir"
+	# download big teeturtle images
+	if echo "$1" | grep -iq "teeturtle.com"
+	then
+		teeDir="$HOME/storage/downloads/TeeTurtle/"
+		mkdir -p "$teeDir"
+		$HOME/bin/download-teeturtle "$1" "$teeDir"
+		termux-media-scan "$teeDir"
+	# download images off this unknown page
+	else
+		outDir="$HOME/storage/downloads/$domain"
+		mkdir -p "$outDir"
+		$HOME/bin/download-page-images "$1" "$outDir"
+		termux-media-scan "$outDir"
+	fi
+# google the tracking number
+elif [ -n "$trackingNum" ]
+then
+	# termux-open-url "https://www.google.com/search?q=$trackingNum"
+	termux-open-url "https://parcelsapp.com/en/tracking/$trackingNum"
 else
-	echo "not sure what to do with this"
+	error="I have no idea what this is."
+	echo "$error"
+	termux-toast "$error"
 	exit 1
 fi
-
